#:kivy 1.9.1

<StructureDraw>:
	canvas.before:
        Color: 
            rgba: 1,0,0,1
        Rectangle:
            pos: 0,0
            size: 300,100
	canvas:
		Color:
			rgba: 0,1,0,1
		Rectangle:
			pos: 100,0
			size: 200,100
	canvas.after:
		Color: 
			rgba: 0,0,1,1
		Rectangle:
			pos: 200,0
			size: 100,100
	Button:
		text: 'long btn'
		pos_hint: {'center_x': .1, 'center_y': .1}
		size_hint: .9,.1


